project:
  type: website
  output-dir: docs

website:
  title: "qalg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Algebra en Ciencia de Datos\1.qmd
      - Gestion de proyectos\scrum_intro.qmd
      - Intro a aprendizaje de maquina\1.qmd
  sidebar: 
    contents: auto

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



