---
title: "3"
---

# Espacios vectoriales

Los sistemas de ecuaciones, matrices, tensores, hacen parte de los espacios vectoriales.

#Importante El conjunto de matrices *invertibles* es un espacio vectorial. (recordar si son invertibles, tienen determinante !=0)

## Definición de un espacio vectorial

#FIXME

Sea $V$ un espacio vectorial real si $\forall x,y,z \in V\ \alpha, \beta \in \mathbb{R}$.

10 propiedades.

\[\[Algebra en Ciencia de Datos/2\]\]

### Subespacio vectorial

Un subconjunto $H$ de $V$ es un subconjunto que también cumple con ser un espacio vectorial.

Para comprobar que algo es subespacio es más fácil. Hay que probar 1. $x+y\in H$ 2. $\alpha x \in H$ #Importante Estas dos propiedades implican que *todo* subespacio debe contener al vector $0$.

Ej: $V=\mathbb{R}^2=\{(x_1,x_2)| x_1,x_2\in \mathbb{R}\}$ $H=\mathbb{R}=\{(x_1,0)| x_1\in \mathbb{R}\}$ H es subespacio vectorial :3

Ej: $H=\{(x,y,z) \in \mathbb{R}^3 : x=at,y=bt,z=ct,\ con\ a,b,c,t \in \mathbb{R} \}$ entonces $x+y=(a(t_1+t_2),b(t_1+t_2), c(t_1+t_2))$ $\alpha x=(\alpha at, \alpha bt, \alpha ct)$ Yay, por tanto H si es subespacio.

### Teorema de Intersección de Subespacios

Si $H_1$ y $H_2$ son subespacios lineales, $H_1\cap H_2$ es un subespacio vectorial

Ej: Si dos planos que pasan por el origen le quiero sacar una intersección, obtengo una recta que pasa por el origen (o plano si $H_1=H_2$ pero ew)

## Algo de chequear independencia lineal

Hay que buscar $c_1c_2c_3$ !=0 que hagan que $$c_1x_1+c_2x_2+c_3x_3=0$$ $$A=|x_1\quad x_2\quad x_3|=|0|$$ Haciendo Gauss Jordan ahí, si hay dependencia, habrá una fila de ceros o \# de columnas pivote menor que columnas.

## Bases y conjuntos generadores

Si un conjunto de vectores $B$, para un espacio vectorial $V$ cumple: 1. $B$ es conjunto generagor de $V$, es decir, $span(B)=V$ 2. Los vectores $b_i \in B$ son linealmente independientes.

Para un $V$ es equivalente decir: $B$ es base de $V$ $B$ es conjunto generador minimal (necesito minimo ese numero de elementos, sino no voy a generar $V$) $B$ es conjunto linealmente maximal (no va a haber un conjunto con mayor numero de elementos, no sería linealmente independiente) Cada vector $x \in V$ se puedes escribir en terminos de los $b_i \in B$

### Cambios de base

si tengo la base canonica en R3 y luego(1,1,0) (0,1,0)(0,0,1)

### Transformaciones lineales

un isomorfismo es una transformación lineal biyectiva (un cambio de base es un isomorfismo) un endomorfismo es una transformación de V en si mismo) y automorfismo (endomorfismo biyectivo)

#### Teorema

Dos espacios vectoriales $V,W$ son isomorfos si, Y SOLO SI BABY si $dim(V)=dim(W)$. Tonces todos los espacios vectoriales de misma dimension son equivalentes, no hay perdida de información.



$$\rho\phi\Phi\gamma\psi\Psi$$

Importante, el kernel (nucleo, espacio nulo) se le sacan bases, chequear si tiene muchos elementos sirve para validar si hay inyectividad.

La Imagen

\$\$\phi:V\rightarrow W\$\$

$$
ker(\phi)=\{v\in V:\phi(v)=o_w\}
$$

Teorema

$$
dim(ker(\phi))+dim(Im(\phi))=dim(V)
$$

Como encontrar una base para una imagen.

IM(A) =...=dim(CA),

1,-1,3

2,0,4

-1,-3,1