---
title: "4"
---

# Espacio métrico

Un espacio métrico es un par $(E,d)$ donde

$E$ es conjunto

## Métricas en aplicaciones

Para comparaciones se traduce en diferentes formas de definir distancias...

Como sea que se definan, usualmente no solo de forma exacta sino que se aproximan (con métodos numéricos) que van a converger (si la métrica permite convergencia, no como una discreta).

### Notas de convergencia

Big O Notation for some reason denota la velocidad con la que una secuencia de $\{x_n\}$ con la que se aproxima a su límite.

La razón debe ser porque si uno ve la secuencia como el tamaño del input inicial pero siendo generado one at a time. Así es como complejidad con base en los datos pero los datos son implícitos en un generador (de los elementos de la secuencia).

k- means funciona muy lindo cuando los datos vienen de mixturas gaussianas (normal multivariada), cuando son como elipses. Otherwise maybe reconsider.

Vector support machine?

## Espacios Normados

Ok es un espacio métrico, pero es un par $(V, ||\cdot||)$ donde V es ahora un espacio vectorial y la norma.

#Importante

No toda métrica proviene de una norma pero toda norma tiene métrica.

Uno tiene que saber calcular cuantos pasos va a tardar un algoritmo dado una métrica y epsilon para.

## Normas matriciales

l espectral se supone que es la euclidiana

l infinito norma inducida es la suma de filas y se saca el máximo

l 1 es suma por columnas y se saca el máximo.

se usa desigualdad de Chebyshev para detección de datos atípicos

```{python}
import polars


```

BTW Para detectar outliers se usan las distancias de Mahalanobis

Esto es un estimador paramétrico (o sa que hay que chequear que se cumplen sus suposiciones)

Para esto hay que chequear que los datos vengan de gaussianas (normal multivariado, hay tests estadísitcos para chequear)

También se usan distancias de

Matrices definidas positivas son matrices donde cada elemento es $a_{ij}\geq 0$

En optimización esto garantiza convexidad

la matriz de covarianza es definida positiva (excepto cuando hay degeneraciones)

permite definir distancias como $||x||^2_A=<x,Ax>$

# Tarea, simular normal multivariada